fixup! release: add Mac OSX installer build
Starting with upstream commit 4580bcd2354a ("osxkeychain: avoid
incorrectly skipping store operation", 2025-11-14), the osxkeychain
credential helper includes git-compat-util.h. That header includes
openssl/ssl.h unless -DNO_OPENSSL is defined:

    ../../../git-compat-util.h:199:10: fatal error:
        'openssl/ssl.h' file not found

On macOS, the main Makefile sets NO_OPENSSL (because Apple Common
Crypto is used instead) and adds -DNO_OPENSSL to BASIC_CFLAGS. But
contrib Makefiles that only include config.mak* files don't get this
logic - they only see the variables, not the Makefile rules that
convert NO_OPENSSL into -DNO_OPENSSL.

Add -DNO_OPENSSL to BASIC_CFLAGS in config.mak so that contrib builds
like osxkeychain can pick it up.

Signed-off-by: Johannes Schindelin <Johannes.Schindelin@gmx.de>