osxkeychain: always apply required build flags
Starting with upstream commit 4580bcd2354a ("osxkeychain: avoid
incorrectly skipping store operation", 2025-11-14), the osxkeychain
credential helper includes git-compat-util.h and links against
libgit.a.

The osxkeychain Makefile has:

    CFLAGS ?= -g -O2 -Wall -I../../.. $(BASIC_CFLAGS)

The ?= operator means "set only if not already set". When building
via a parent Makefile that passes CFLAGS on the command line, this
entire assignment is ignored - including the -I../../.. needed to find
git-compat-util.h and the $(BASIC_CFLAGS) needed for -DNO_OPENSSL:

    git-credential-osxkeychain.c:5:10: fatal error:
        'git-compat-util.h' file not found

Using += instead of ?= is not sufficient either, because command-line
variables in Make override even += assignments. We need to use
"override CFLAGS +=" to force these flags to be appended regardless
of how CFLAGS was set.

Signed-off-by: Johannes Schindelin <Johannes.Schindelin@gmx.de>